### ISSUE TITLE
Ability to define priority among channel partners from the dashboard.

### ISSUE THREAD

**Issue by prshant70** [tata1mg/notifyone#17]
Add capability to define priority among channel partners for a channel from the dashboard.

This will be used as default priority and selection of channel partners for notification to be sent will be based on this priority.

**Comment by sanyamgandhak** [comment]
Please assign this to me

**Comment by prshant70** [comment]
@sanyamgandhak 
Sorry, I was already working on it and forgot to assign it to myself. Changes are already done and will be merge soon.
I encourage you to pick any other open issue from the list.
