### ISSUE TITLE
Notify-Dashboard Submodule not loading

### ISSUE THREAD

**Issue by manikandantk88** [tata1mg/notifyone#19]
Hi,

I am trying to setup using docker. I am not able to update submodules of the repository. Facing Notify Dashboard repository not found error. Could you please help?
https://github.com/tata1mg/notifyone-dashboard/tree/36b4d549f00d39f13dfbdf6b8fccd7c45ae7e187
@prshant70

**Comment by prshant70** [comment]
@manikandantk88 Thanks for reporting this.
There was some issue with the notifyone-dashboard repository and we took it down (made private for now). Just wait for a couple of days, we are about to release a new revamped version of the dashboard that has a lot of new features and customizations. We will rollout the changes by next week.
If you still face any issues or have other quires regarding NotifyOne, you can reach out to the maintainers of the product @ notifyone@1mg.com

**Comment by prshant70** [comment]
@manikandantk88 
Hey, the latest release is out.
Please point to the new release of NotifyOne - https://github.com/tata1mg/notifyone/releases/tag/2.0.0
The new release addresses the changes faced by you previously and a lot more feature additions.

**Comment by manikandantk88** [comment]
@prshant70 Thank you 👍
